Stdg 289 tooltip
Studi-Guide/Studi-Guide pull request #107
Opened 2021-01-02 23:47 UTC by 070108111

2021-01-02 23:53 UTC, 070108111 commented
Bisher erfolgreich getestet mit:

- Linux Chromium Version 87.0.4280.88 (Offizieller Build) snap (64-Bit)
- Linux 83.0 (64-Bit)
- Android 9 Chrome 87.0.4280.101
- Android 9 Firefox 84.1.2

2021-01-03 13:09 UTC, NoUmlautsAllowed requested changes

2021-01-03 13:09 UTC, NoUmlautsAllowed commented on front/src/app/stdg-tooltip/stdg-tooltip.component.scss
> +  box-shadow: 0 0 6px 2px rgba(110, 110, 110, 0.4);
Hier vielleicht lieber eine border mit shadow wie der Drawer anstatt dem background einen Gradient zu geben? Finde border+shadow passt besser zum Ionic Design.

2021-01-03 13:09 UTC, NoUmlautsAllowed commented on front/src/app/stdg-tooltip/stdg-tooltip.component.scss
> +  background: #242424;
und die `var()` Funktion um die Farben aus dem Ionic Theme zu holen 👍

2021-01-03 15:20 UTC, NoUmlautsAllowed approved these changes
👍

2021-01-03 15:43 UTC, merged