STDG 88
Studi-Guide/Studi-Guide pull request #63
Opened 2020-08-23 15:31 UTC by NoUmlautsAllowed

Möglichkeit, die Sprache zwischen Deutsch und Englisch zu wählen.

Implementierung mit Angulars i18n.

2020-08-26 21:42 UTC, NoUmlautsAllowed commented
Internationalisierung und Sprachauswahl ist implementiert. Beim Build kommt ein Fehler, wenn nicht alle Übersetzungen vorhanden sind. Könnte aber auch noch in der Konfiguration geändert werden.

Prinzipiell kann die Sprache geändert werden. Evtl. gibt es aber noch eine elegantere Möglichkeit mit dem Angular Router, da würde ich nochmal nachschauen. Ich denke den Rest könnt ihr euch aber schon mal anschauen :+1: 

Übersetztung von Templates schaue ich mir auch nochmal an, dann hätten wir dafür auch gleich ein Beispiel :smile:

2020-08-28 09:02 UTC, sharpSteff approved these changes
fett

2020-08-28 09:31 UTC, sharpSteff requested changes
Settings-Tab muss noch mit Intelligenz versorgt werden

2020-08-28 09:32 UTC, sharpSteff commented
Tab4Page zeigt immer "English" an obwohl die Seite deutsch ist.
Auch haben die html element kein i18n-tag

2020-08-29 06:30 UTC, NoUmlautsAllowed commented
Übersetzung für Einstellungen und Sprachauswahl hinzugefügt.

2020-08-30 20:19 UTC, 070108111 approved these changes
:+1:

2020-08-31 05:48 UTC, merged